In [1]:
import numpy as np
from scipy.linalg import null_space, cholesky, inv

In [15]:
def calc_w(vp1, vp2, vp3):
    x1, y1 = vp1
    x2, y2 = vp2
    x3, y3 = vp3
    A = np.array([[(x1*x2)+(y1*y2), x1+x2, y1+y2, 1],
                   [(x1*x3)+(y1*y3), x1+x3, y1+y3, 1],
                   [(x3*x2)+(y3*y2), x3+x2, y3+y2, 1]])
    w = null_space(A)
    print(w)
    w /= w[3]
    return np.array([[w[0],  0,   w[1]],
                     [0,    w[0], w[2]],
                     [w[1], w[2], w[3]]], dtype=np.float32)

In [16]:
vp1 = (212, 2138)
vp2 = (-49, 42)
vp3 = (1105, 146)
W = calc_w(vp1, vp2, vp3)
W

[[ 2.01106375e-06]
 [-7.71090140e-04]
 [-4.74314884e-04]
 [ 9.99999590e-01]]


array([[ 2.0110647e-06,  0.0000000e+00, -7.7109045e-04],
       [ 0.0000000e+00,  2.0110647e-06, -4.7431508e-04],
       [-7.7109045e-04, -4.7431508e-04,  1.0000000e+00]], dtype=float32)

In [20]:
K = inv(cholesky(W))
K/=K[2][2]
K

array([[542.77856,  -0.     , 383.42398],
       [  0.     , 542.77856, 235.85274],
       [  0.     ,   0.     ,   1.     ]], dtype=float32)