In [3]:
import numpy as np
from scipy.linalg import null_space, cholesky, inv

## $\omega$ calculation

If we consider that the camera has square pixels and no skewness in the les, we can define $\omega$ is of the form:
$$
\omega = 
\begin{bmatrix}
\omega_1   &   0          & \omega_2 \\
0          &   \omega_1   & \omega_3 \\
\omega_2   &   \omega_3   & \omega_4 
\end{bmatrix}
$$

Where $\omega$ is defined as $\omega = (KK^{T})^{-1}$

Since the vanishing points are orthogonal by definition, we calculate the matrix $\omega$ as the null space of A for the system of equations:
$$ V_1^{T} \omega V2 = 0 $$
$$ V_1^{T} \omega V3 = 0 $$
$$ V_3^{T} \omega V2 = 0 $$

Where the vanishing points are defined as:

$$
V_1 =
\begin{bmatrix}
x_1 \\ 
y_1 \\ 
1
\end{bmatrix}
;V_2 =
\begin{bmatrix}
x_2 \\ 
y_2 \\ 
1
\end{bmatrix}
;
V_3 =
\begin{bmatrix}
x_3 \\ 
y_3 \\ 
1
\end{bmatrix}
$$

This system can be rewritten in the form of $A\omega = 0$ where $\omega = [\omega_1, \omega_2, \omega_3, \omega_4]^{T}$ is in a vectorized form and $A$ is defined as:

$$
A \omega =
\begin{bmatrix}
x_1 x_2 + y_1 y_2   &   x_2 y_1+x_1   &   y_1 + y_2   &   1 \\
x_1 x_3 + y_1 y_3   &   x_3 y_1+x_1   &   y_1 + y_3   &   1 \\
x_3 x_2 + y_3 y_2   &   x_2 y_3+x_3   &   y_3 + y_2   &   1
\end{bmatrix}
\begin{bmatrix}
\omega_1 \\
\omega_2 \\
\omega_3 \\
\omega_4 \\
\end{bmatrix} =
0
$$

In [4]:
def calc_w(vp1, vp2, vp3):
    x1, y1 = vp1
    x2, y2 = vp2
    x3, y3 = vp3
    A = np.array([[(x1*x2)+(y1*y2), x2*y1+x1, y1+y2, 1],
                   [(x1*x3)+(y1*y3), x3*y1+x1, y1+y3, 1],
                   [(x3*x2)+(y3*y2), x2*y3+x3, y3+y2, 1]])
    w = null_space(A)
    print(w)
    w /= w[3]
    return np.array([[w[0],  0,   w[1]],
                     [0,    w[0], w[2]],
                     [w[1], w[2], w[3]]], dtype=np.float32)

In [5]:
vp1 = (212, 2138)
vp2 = (-49, 42)
vp3 = (1105, 146)
W = calc_w(vp1, vp2, vp3)
W

[[ 1.64898548e-05]
 [-3.07032838e-06]
 [-1.20661857e-03]
 [ 9.99999272e-01]]


array([[ 1.6489867e-05,  0.0000000e+00, -3.0703306e-06],
       [ 0.0000000e+00,  1.6489867e-05, -1.2066194e-03],
       [-3.0703306e-06, -1.2066194e-03,  1.0000000e+00]], dtype=float32)

## K calculation
Since $\omega$ is defined as
$$
\omega = (K K^T)^{-1}
$$

We can easily obtain the intrinsic parameters of the camer $K$ by decomposing $\omega$ through the Cholesky factorization and obtaining its inverse.

In [8]:
K = inv(cholesky(W))
K /= K[2][2]
K

array([[ 2.3513597e+02, -0.0000000e+00,  1.8619499e-01],
       [ 0.0000000e+00,  2.3513597e+02,  7.3173386e+01],
       [ 0.0000000e+00,  0.0000000e+00,  1.0000000e+00]], dtype=float32)